/* Espera 11 minutos después de hacer los cambios en tu sitio, para depués
 * actualizar este archivo. */
const CACHE = "gilpgijs-2.01";

/** Archivos requeridos para que la aplicación funcione fuera de línea. */
const ARCHIVOS = [
  "/b_sw.html",
  "/favicon.ico",
  "/index.html",
  "/LICENSE",
  "/site.webmanifest",
  "cmp/mi-nav.js",
  "css/estilos.css",
  "c_fundamentos/1_proceso.html",
  "c_fundamentos/2_algoritmo.html",
  "c_fundamentos/3_diagrama.html",
  "c_fundamentos/4_pseudocodigo.html",
  "c_fundamentos/5_lenguaje.html",
  "c_fundamentos/6_resumen.html",
  "d_js/1_js.html",
  "d_js/2_textos.html",
  "d_js/3_string.html",
  "d_js/4_console.html",
  "d_js/5_orden.html",
  "d_js/7_resumen.html",
  "d_js/6_pres/1.html",
  "d_js/6_pres/2.html",
  "d_js/6_pres/3.html",
  "d_js/6_pres/index.html",
  "d_js/img/Cadena.svg",
  "d_js/img/Eslabon.svg",
  "d_js/img/winlogo.png",
  "d_js/img/winlogo.xcf",
  "e_variables/10_resumen.html",
  "e_variables/1_identificadores.html",
  "e_variables/2_variables.html",
  "e_variables/4_constantes.html",
  "e_variables/5_duplicadas.html",
  "e_variables/6_no_encontradas.html",
  "e_variables/7_bloques.html",
  "e_variables/8_pres_bloque.html",
  "e_variables/9_pres_bloque_v_d.html",
  "e_variables/3_pres_var/1.html",
  "e_variables/3_pres_var/2.html",
  "e_variables/3_pres_var/3.html",
  "e_variables/3_pres_var/4.html",
  "e_variables/3_pres_var/5.html",
  "e_variables/3_pres_var/6.html",
  "e_variables/3_pres_var/7.html",
  "e_variables/3_pres_var/8.html",
  "e_variables/3_pres_var/9.html",
  "e_variables/3_pres_var/index.html",
  "f_comentarios/1_comentarios.html",
  "f_comentarios/2_com_1.html",
  "f_comentarios/4_com_1_o_mas.html",
  "f_comentarios/6_JsDoc.html",
  "f_comentarios/7_resumen.html",
  "f_comentarios/3_pres_com_1/1.html",
  "f_comentarios/3_pres_com_1/2.html",
  "f_comentarios/3_pres_com_1/index.html",
  "f_comentarios/5_pres_1_o_mas/1.html",
  "f_comentarios/5_pres_1_o_mas/2.html",
  "f_comentarios/5_pres_1_o_mas/3.html",
  "f_comentarios/5_pres_1_o_mas/index.html",
  "g_if/1_boolean.html",
  "g_if/2_txt_igualdad.html",
  "g_if/3_if.html",
  "g_if/4_if_true.html",
  "g_if/5_if_false.html",
  "g_if/7_resumen.html",
  "g_if/6_if_programa/2_problema.html",
  "g_if/6_if_programa/3_escenarios.html",
  "g_if/6_if_programa/4_diseno.html",
  "g_if/6_if_programa/5_codigo.html",
  "g_if/6_if_programa/6_replit.html",
  "g_if/6_if_programa/7_vsc.html",
  "g_if/6_if_programa/index.html",
  "g_if/img/if.svg",
  "h_if_else/1_if_else.html",
  "h_if_else/2_if_else_true.html",
  "h_if_else/3_if_else_false.html",
  "h_if_else/5_resumen.html",
  "h_if_else/4_if_else_programa/2_problema.html",
  "h_if_else/4_if_else_programa/3_escenarios.html",
  "h_if_else/4_if_else_programa/4_diseno.html",
  "h_if_else/4_if_else_programa/5_codigo.html",
  "h_if_else/4_if_else_programa/index.html",
  "h_if_else/img/if-else.svg",
  "img/icono1024.png",
  "img/icono2048.png",
  "img/icono256.png",
  "i_multiple/1_multiple.html",
  "i_multiple/2_pres_m_1_true.html",
  "i_multiple/3_pres_m_2_true.html",
  "i_multiple/4_pres_m_false.html",
  "i_multiple/6_resumen.html",
  "i_multiple/5_m_prog/2_problema.html",
  "i_multiple/5_m_prog/3_escenarios.html",
  "i_multiple/5_m_prog/4_diseno.html",
  "i_multiple/5_m_prog/5_codigo.html",
  "i_multiple/5_m_prog/index.html",
  "i_multiple/img/condicional-multiple.svg",
  "js/config.js",
  "j_melse/1_melse.html",
  "j_melse/2_pres_melse_1_true.html",
  "j_melse/3_pres_melse_2_true.html",
  "j_melse/4_pres_melse_false.html",
  "j_melse/6_resumen.html",
  "j_melse/5_melse_prog/2_problema.html",
  "j_melse/5_melse_prog/3_escenarios.html",
  "j_melse/5_melse_prog/4_diseno.html",
  "j_melse/5_melse_prog/5_codigo.html",
  "j_melse/5_melse_prog/index.html",
  "j_melse/5_melse_prog/img/condicional-multiple-else.svg",
  "j_melse/img/condicional-multiple-else.svg",
  "j_melse/img/condicional-multiple.svg",
  "k_textos/1_number.html",
  "k_textos/2_concatenacion.html",
  "k_textos/3_asignacion.html",
  "k_textos/4_plantillas.html",
  "k_textos/5_orden.html",
  "k_textos/6_orden_igualdad.html",
  "k_textos/7_resumen.html",
  "lib/layout-cajon.js",
  "lib/layout-cajon_shadow.js",
  "lib/mi-footer.js",
  "lib/muestra-codigo.js",
  "lib/muestra-codigo_shadow.js",
  "lib/utilHtml.js",
  "lib/css/estilos.css",
  "lib/css/gentium-book-basic-v11-latin-700.woff",
  "lib/css/gentium-book-basic-v11-latin-700.woff2",
  "lib/css/gentium-book-basic-v11-latin-700italic.woff",
  "lib/css/gentium-book-basic-v11-latin-700italic.woff2",
  "lib/css/gentium-book-basic-v11-latin-italic.woff",
  "lib/css/gentium-book-basic-v11-latin-italic.woff2",
  "lib/css/gentium-book-basic-v11-latin-regular.woff",
  "lib/css/gentium-book-basic-v11-latin-regular.woff2",
  "lib/css/gentium-book-basic.css",
  "lib/css/material-icons.css",
  "lib/css/MaterialIcons-Regular.codepoints",
  "lib/css/MaterialIcons-Regular.ttf",
  "lib/css/mi-footer.css",
  "lib/css/prueba.css",
  "lib/css/ubuntu-mono-v10-latin-700.woff",
  "lib/css/ubuntu-mono-v10-latin-700.woff2",
  "lib/css/ubuntu-mono-v10-latin-700italic.woff",
  "lib/css/ubuntu-mono-v10-latin-700italic.woff2",
  "lib/css/ubuntu-mono-v10-latin-italic.woff",
  "lib/css/ubuntu-mono-v10-latin-italic.woff2",
  "lib/css/ubuntu-mono-v10-latin-regular.woff",
  "lib/css/ubuntu-mono-v10-latin-regular.woff2",
  "lib/css/ubuntu-mono.css",
  "lib/css/ubuntu-v15-latin-700.woff",
  "lib/css/ubuntu-v15-latin-700.woff2",
  "lib/css/ubuntu-v15-latin-700italic.woff",
  "lib/css/ubuntu-v15-latin-700italic.woff2",
  "lib/css/ubuntu-v15-latin-italic.woff",
  "lib/css/ubuntu-v15-latin-italic.woff2",
  "lib/css/ubuntu-v15-latin-regular.woff",
  "lib/css/ubuntu-v15-latin-regular.woff2",
  "lib/css/ubuntu.css",
  "l_logicos/1_op_y.html",
  "l_logicos/2_op_o.html",
  "l_logicos/3_op_no.html",
  "l_logicos/4_op_ternario.html",
  "l_logicos/5_resumen.html",
  "l_logicos/index.html",
  "m_do_while/1_do_while.html",
  "m_do_while/2_pres_do_while.html",
  "m_do_while/4_resumen.html",
  "m_do_while/3_do_while_prog/2_problema.html",
  "m_do_while/3_do_while_prog/3_escenarios.html",
  "m_do_while/3_do_while_prog/4_diseno.html",
  "m_do_while/3_do_while_prog/5_codigo.html",
  "m_do_while/3_do_while_prog/index.html",
  "m_do_while/img/do-while.svg",
  "n_numeros/10_resumen.html",
  "n_numeros/1_recta.html",
  "n_numeros/2_ops_num.html",
  "n_numeros/3_asignacion.html",
  "n_numeros/4_incr_y_decr.html",
  "n_numeros/5_igualdad.html",
  "n_numeros/6_orden.html",
  "n_numeros/7_orden_igualdad.html",
  "n_numeros/8_precedencia.html",
  "n_numeros/9_expresiones.html",
  "n_numeros/img/cuadratica.png",
  "n_numeros/img/recta.png",
  "n_numeros/img/recta.svg",
  "o_while/1_while.html",
  "o_while/2_pres_while_asc.html",
  "o_while/3_pres_while_asc_2.html",
  "o_while/4_pres_while_desc.html",
  "o_while/5_pres_while_desc_2.html",
  "o_while/6_pres_while_no_ejec.html",
  "o_while/7_pres_while_desc_mal.html",
  "o_while/8_pres_while_asc_mal.html",
  "o_while/9_resumen.html",
  "o_while/img/while.svg",
  "p_for/1_for.html",
  "p_for/2_pres_for.html",
  "p_for/4_resumen.html",
  "p_for/3_for_prog/2_problema.html",
  "p_for/3_for_prog/3_escenarios.html",
  "p_for/3_for_prog/4_diseno.html",
  "p_for/3_for_prog/5_codigo.html",
  "p_for/3_for_prog/index.html",
  "p_for/img/for.svg",
  "q_switch/1_switch.html",
  "q_switch/2_pres_switch_c.html",
  "q_switch/3_pres_switch_c_v.html",
  "q_switch/4_pres_switch_c_v2.html",
  "q_switch/5_pres_switch_c_s_b.html",
  "q_switch/6_pres_switch_c_n.html",
  "q_switch/7_switch_default.html",
  "q_switch/8_pres_switch_default.html",
  "q_switch/9_resumen.html",
  "q_switch/cmp/ctrl-diapositiva.js",
  "q_switch/cmp/nav-local.js",
  "q_switch/img/switch-default.svg",
  "q_switch/img/switch.svg",
  "/"
];

self.addEventListener("install", evt => {
  console.log("Service Worker instalado.");
  // @ts-ignore
  evt.waitUntil(cargaCache());
});

self.addEventListener("fetch", evt => {
  // @ts-ignore
  if (evt.request.method === "GET") {
    // @ts-ignore
    evt.respondWith(usaCache(evt));
  }
});

self.addEventListener("activate", () => console.log("Service Worker activo."));

async function cargaCache() {
  console.log("Intentando cargar cache: " + CACHE);
  const cache = await caches.open(CACHE);
  await cache.addAll(ARCHIVOS);
  console.log("Cache cargado: " + CACHE);
}

async function usaCache(evt) {
  const cache = await caches.open(CACHE);
  const response = await cache.match(evt.request, { ignoreSearch: true });
  if (response) {
    return response;
  } else {
    return fetch(evt.request);
  }
}