// Menor que (<)
console.log("0" < "A");   //true
console.log("A" < "a");   //true
console.log("a" < "b");   //true
console.log("ah" < "aa"); //false
console.log("ah" < "ah"); //false
console.log("ah" < "ai"); //true
// Mayor que (>)
console.log("ah" > "aa"); //true
console.log("ah" > "ah"); //false
console.log("ah" > "ai"); //false